include ../make.meson.inc

NAME     := pywrapper
MAKEFILE := $(lastword $(MAKEFILE_LIST))

LIBSRC_WRAP_FPP_FILES := main.f90

test: build1
	$(PYTHON) docstring_test.py

build1:
	$(MAKE) -f $(MAKEFILE) build NAME=$(NAME) LIBSRC_WRAP_FPP_FILES=$(LIBSRC_WRAP_FPP_FILES)

