# Callback examples require special build steps (static library, --callback flag)
# that make.meson.inc doesn't support. Delegate to the regular Makefile.

test:
	$(MAKE) -f Makefile test

clean:
	$(MAKE) -f Makefile clean
