include ../make.meson.inc

NAME     := pywrapper_no_sign

test: build
	echo "TODO: Fix meson build for tests without signatures"
	# $(PYTHON) tests_no_sign.py
	echo "TODO: Add tests_sign.py once meson build support signatures"
	# $(PYTHON) tests_sign.py
